.TH LIBERTREE 1

.SH NAME

Libertree - free, libre, open-source software intended to provide a way for
people to create their own social network

.SH SYNOPSIS

libertree [options] <command> [command options]

.SH DESCRIPTION

Libertree is free, libre, open-source software which is intended to provide a
way for people to create their own social network.  Libertree social networks
can be free from commercial influence and manifestation, such as behaviour
tracking, user profiling, advertising, data mining and analysis, and covert
information filtering.

.SH OPTIONS

-h, --help
.TP
-v, --version

.SH COMMANDS

.SS requirements-check

Lorem ipsum

.SS install [options]

Lorem ipsum

.SS update

Lorem ipsum

.SS start <frontend|backend|frontend-jobs|backend-jobs|websockets|exporter>

Lorem ipsum

.SS stop <frontend|backend|frontend-jobs|backend-jobs|websockets|exporter>

Lorem ipsum

.SS restart <frontend|backend|frontend-jobs|backend-jobs|websockets|exporter>

Lorem ipsum

.SH ENVIRONMENT VARIABLES

.SS LIBERTREE_ENV

The Libertree environment to run under.  One of: production, test, development .
This affects which database is used.

.SH EXAMPLES

Lorem ipsum

.SH SOURCE CODE

https://github.com/Libertree

.SH AUTHORS

Libertree is written by Pistos and rekado, with some contributions from others.
See the git repositories for names of other contributors.  Visit them at
irc.freenode.net #libertree .

.SH REPORTING BUGS

Please report issues on Libertree itself, in The First Forest. Use hashtags,
including #bug or #bugs.

