.TH LIBERTREE 1

.SH NAME

Libertree - free, libre, open-source software intended to provide a way for
people to create their own social network

.SH SYNOPSIS

libertree [options] <command> [command options]

.SH DESCRIPTION

Lorem ipsum

.SH OPTIONS

Lorem ipsum

.SH COMMANDS

Lorem ipsum

.SH ENVIRONMENT VARIABLES

.SS LIBERTREE_ENV
The Libertree environment to run under.  One of: production, test, development .

.SH EXAMPLES

Lorem ipsum

.SH AUTHORS

Libertree is written by Pistos and rekado, with some contributions from others.
See the git repositories for names of other contributors.

.SH REPORTING BUGS

Please report issues on Libertree itself.  Use hashtags, including #bug or #bugs.

