source 'http://ruby.taobao.org'

gem 'mail'
gem 'mail-gpg'
gem 'libertree-model', :git => 'git://github.com/Libertree/libertree-model-rb.git'
gem 'libertree-client', :git => 'git://github.com/Libertree/libertree-client-rb.git'
gem 'json'
gem 'sequel'

group 'libertree-model' do
  gem 'ruby-oembed'
end

group 'extensions' do
  gem 'pg'
  gem 'blather'
  gem 'bcrypt-ruby'
end