source 'http://rubygems.org'

gem 'm4dbi'
gem 'rdbi', :git => 'git://github.com/RDBI/rdbi.git'
gem 'rdbi-driver-postgresql', :git => 'git://github.com/RDBI/rdbi-driver-postgresql.git', :branch => 'fix-execute-memory-leak'
gem 'mail'
gem 'mail-gpg'
gem 'libertree-model', :git => 'git://github.com/Libertree/libertree-model-rb.git', :branch => 'xmpp'
gem 'libertree-client', :git => 'git://github.com/Libertree/libertree-client-rb.git', :branch => 'xmpp'
gem 'json'

group 'libertree-model' do
  gem 'ruby-oembed'
end

group 'extensions' do
  gem 'pg'
  gem 'blather'
  gem 'bcrypt-ruby'
end