#!/usr/bin/env bash

intro() {
  clear
  cat <<EOF
==================================
Welcome to The Libertree Installer
==================================

The installer will attempt to fulfill the following tasks:

  1. Create a system user for libertree
  2. Install libertree as that system user.
     This includes:
       - install RVM and Ruby 1.9.3 in RVM
       - setup a PostgreSQL owner and databases
       - install the Libertree Ruby backend
       - install the Libertree Ramaze frontend

To install system packages you will need root privileges.  If sudo is installed
you may need to input your password to execute certain tasks as root.  For
database administration you may need the password of the PostgreSQL superuser
on some systems.

You should have installed all dependencies before running this script.

Press a key to continue
EOF
  read -n1
  clear
}

wizard() {
  safety on
  intro
  create_system_user
  install_as_system_user
  say "\nYour Libertree has been planted. For further instructions,"
  say "please refer to USAGE.md in the root directory."
}

# save original working directory and always return to it on exit
orig_dir=$(pwd)
trap "cd $orig_dir" EXIT

cd $(dirname $0)
for file in ./functions/*; do
  source $file
done

wizard
