#!/usr/bin/env bash

intro() {
  clear
  cat <<EOF
==================================
Welcome to The Libertree Installer
==================================

The installer will attempt to fulfill the following tasks:

  1. Create a system user for libertree
  2. Install libertree as that system user.
     This includes:
       - install the latest version of bundler as a local gem
       - setup a PostgreSQL owner and databases
       - install the Libertree Ruby backend
       - install the Libertree Ramaze frontend

If sudo is installed you may need to input your password to execute
certain tasks as root.

You should have installed all runtime dependencies before continuing.
These include:

  ruby postgresql gpgme openssl
EOF

  dev_dependencies
  say "\nPress a key to continue (or Ctrl-C to abort)"
  read -n1
  clear

  cat<<EOF
Database configuration
------------------------

To simplify database administration, please configure PostgreSQL to
trust local connections.  Please confirm that the configuration file
\`pg_hba.conf' contains the following lines:

    local  all  all       trust
    local  all  postgres  trust

If you see \`peer', \`ident', or \`md5' instead of \`trust', please
change the lines and reload the PostgreSQL server configuration (or
restart the postgresql daemon).  While this change is not required, it
is highly recommended because authentication often gets in the way.

Common locations of the pg_hba.conf file are:

   Debian & Ubuntu Server:
     /etc/postgresql/9.1/main/pg_hba.conf

   Fedora:
     /var/lib/pgsql/data/pg_hba.conf
EOF

  say "\nPress a key to continue (or Ctrl-C to abort)"
  read -n1
  clear
}

dev_dependencies() {
  if [ ! -e /etc/os-release ]; then return 0; fi

  OS=`sed -ne 's/^ID=\(.*\)/\1/p' /etc/os-release`
  case "$OS" in
      debian|ubuntu)
          cat<<EOF
To install the development dependencies, please first run

    apt-get install gcc g++ make ruby1.9-dev libpq-dev libglib2.0-dev libcurl-dev libmagic-dev
EOF
          ;;
      fedora)
          cat<<EOF
To install the development dependencies, please first run

    yum install gcc g++ make ruby-devel postgresql-devel glib2-devel libcurl-devel file-devel
EOF
          ;;
      *)
          cat<<EOF
You may have to install development dependencies first before installing Libertree.  Unfortunately, we could not reliably identify your system, so we cannot name the actual packages you may be needing.

These tools are required:

    gcc g++ make

Development headers for the following software are needed at build time:

    ruby postgresql glib2 libcurl libmagic/file
EOF
          ;;
  esac
  return 0
}

wizard() {
  safety on
  intro
  create_system_user
  install_as_system_user
  say "\nYour Libertree has been planted. For further instructions,"
  say "please refer to USAGE.md in the root directory."
}

# save original working directory and always return to it on exit
orig_dir=$(pwd)
trap "cd $orig_dir" EXIT

cd $(dirname $0)
for file in ./functions/*; do
  source $file
done

wizard
